name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.MY_GITHUB_TOKEN }}" ]; then  
            echo "YOUR_SECRET is not set!"  
          else  
            echo "YOUR_SECRET is set. ${{secrets.MY_GITHUB_TOKEN}}" 
          fi
